In [1]:
from numpy import*
import time
print('\tMULTIPLICACIÓN DE MATRICES')
n=5
C=zeros([n,n])
A=zeros([n,n])
for i in range(0,n):
  for j in range(0,n):
    for k in range(0,n):
      A[i][j]=C[i][k]*C[k][j]
print('\nC_',n,'x',n,'=\n',C)
print('\nA_',n,'x',n,'= C*C =\n',A)
ts=time.time()
print('\nEl tiempo de computo es t = ',time.time()-ts)


	MULTIPLICACIÓN DE MATRICES

C_ 5 x 5 =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

A_ 5 x 5 = C*C =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

El tiempo de computo es t =  4.220008850097656e-05


In [2]:
from numpy import*
import time
print('\tMULTIPLICACIÓN DE MATRICES')
n=5
C=zeros([n,n])
print('\nC_',n,'x',n,'=\n',C)
print('\nA_',n,'x',n,'= C*C =\n',dot(C,C))
ta=time.time()
print('\nEl tiempo de computo por solución propia de Python es t = ',time.time()-ta)


	MULTIPLICACIÓN DE MATRICES

C_ 5 x 5 =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

A_ 5 x 5 = C*C =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

El tiempo de computo por solución propia de Python es t =  0.00012803077697753906


# CÁLCULO DE INTEGRALES

Resolver la integral $\int_{-1}^{1}\sqrt{1-x^{2}}dx$

*  **Método del rectángulo (Riemman)**

Resolviendo la integral con un vector

In [17]:
from numpy import*
I=[]
N=1000
h=2/N
for k in range(1,N):
  x=-1+(k*h)
  y=sqrt((1-x**2))
  i=h*y
  I.append(i)
  It=sum(I)
print('El valor de la integral es I =',It)

El valor de la integral es I = 1.5707437385010703


Resolviendo la integral con un contador

In [23]:
N=1000
h=2/N
It=0
for k in range(1,N):
  x=-1+(k*h)
  y=sqrt((1-x**2))
  i=h*y
  It+=i
print('El valor de la integral es I =',It)

El valor de la integral es I = 1.570743738501071


* **Método del trapezoide**

Resolver la integral $\int_{0}^{1}\sqrt{1-x^{2}}dx$

In [56]:
N=1000
a=-1
b=1
h=(b-a)/N
it=0
for k in range(1,N-1):
    x=a+k*h
    y=sqrt((1-x**2))
    it+=h*y
It=(h/2)*(sqrt(1-a**2)+sqrt(1-b**2))+it
print('El valor de la integral es I =',It)
error=abs((1-(It)*(2/pi)))
print('El error es e =',error*100)

El valor de la integral es I = 1.5706173106560368
El error es e = 0.011396521357098788


Resolver la integral $\int_{0}^{2} (x^{4}-2x+1) dx$

In [66]:
N=1000
a=0
b=2
h=(b-a)/N
it=0
for k in range(1,N-1):
    x=a+k*h
    y=(x**4-(2*x)+1)
    it+=h*y
It=(h/2)*(a**4-(2*a)+1+b**4-(2*b)+1)+it
print('El valor de la integral es I =',It)
error=abs((1-(It)*(1/4.4)))
print('El error es e =',error*100)

El valor de la integral es I = 4.374130474793567
El error es e = 0.5879437546916555


* **Método de Simpson**

Resolver la integral $\int_{0}^{2} (x^{4}-2x+1) dx$

In [29]:
N=1000
a=0
b=2
h=(b-a)/N
it=0
for k in range(1,N//2):
    #x1=a+2*(k-1)*h
    #x2=a+2*k*h
    #x=4*x1+2*x2
    x=(4*(a+(2*k-1)*h))+(2*(a+k*(2*h)))
    y=(x**4-(2*x)+1)
    it+=h*y
It=(h/3)*((a**4-(2*a)+1)+(b**4-(2*b)+1)+it)
print('El valor de la integral es I =',It)
#error=abs((1-(It)*(1/4.4)))
#print('El error es e =',error*100)

El valor de la integral es I = 5.478372294899295


In [50]:
N=1000
a=0
b=2
h=(b-a)/N
it1=0
it2=0
for k in range(1,N//2):
    x1=a+(2*k-1)*h
    y1=(x1**4-(2*x1)+1)
    it1+=y1
for k in range(1,(N//2)-1):
    x2=a+(2*k*h)
    y2=(x2**4-(2*x2)+1)
    it2+=y2
I=4*it1+2*it2
It=(h/3)*((a**4-2*a+1+b**4-2*b+1)+I)
print('El valor de la integral es I =',It)
error=abs((1-(It)*(1/4.4)))
print('El error es e =',error*100)

El valor de la integral es I = 4.348319232857216
El error es e = 1.1745628896087212


### Aplicando los métodos integrales a un conjunto de datos

In [2]:
from numpy import* 
from pylab import*
data = loadtxt("velocities.txt",float)
#plot(data[:,0],data[:,1])
N=100
a=0
b=100
va=data[0,1]
vb=data[100,1]
h=(b-a)/N
it=0
for k in range(1,N-1):
    y=(data[:,1])
    it+=y*h
It=(h/2)*(va+vb)+it
I=sum(It)
print('El valor de la posición es x =',I)

El valor de la posición es x = 839.0166979999995


AttributeError: module 'matplotlib.colors' has no attribute 'to_rgba'